# =========================================
# Stage: Development (Next.js)
# =========================================

ARG NODE_VERSION=22-alpine

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]